version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build:
    # in case we need a larger machine with more threads
    #resource_class: large
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Start containers and run tests
          command: |
            # Memgraph
            wget https://download.memgraph.com/memgraph/v1.0.0/docker/memgraph-1.0.0-community-docker.tar.gz
            docker load -i memgraph-1.0.0-community-docker.tar.gz
            docker run -p 17687:7687 memgraph
            # Neo4j
            docker run -p 7474:7474 -p 7687:7687 --env=NEO4J_AUTH=none neo4j:3.5
            gradle build -x test

      - slack/status
